const EventTypes = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  VIEW_CUSTOMER: "VIEW_CUSTOMER",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",

  VIEW_ACCOUNT: "VIEW_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",

  EXPORT_DATA: "EXPORT_DATA",

  APPROVE_LOAN: "APPROVE_LOAN",
  REJECT_LOAN: "REJECT_LOAN",

  CHANGE_ROLE: "CHANGE_ROLE",

  SYSTEM_CONFIGURATION: "SYSTEM_CONFIGURATION",
});

export default EventTypes;