const Permissions = Object.freeze({
  VIEW_USERS: "VIEW_USERS",
  CREATE_USERS: "CREATE_USERS",
  UPDATE_USERS: "UPDATE_USERS",
  DELETE_USERS: "DELETE_USERS",

  VIEW_EVENTS: "VIEW_EVENTS",
  CREATE_EVENTS: "CREATE_EVENTS",

  VIEW_ALERTS: "VIEW_ALERTS",
  UPDATE_ALERTS: "UPDATE_ALERTS",

  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  VIEW_SESSIONS: "VIEW_SESSIONS",

  VIEW_RISK_ANALYSIS: "VIEW_RISK_ANALYSIS",

  MANAGE_SYSTEM: "MANAGE_SYSTEM",
});

export default Permissions;